In [ ]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import KFold
from sklearn import metrics
from numpy import array
from numpy import argmax
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearnex import patch_sklearn
patch_sklearn()

In [2]:
data_1 = pd.read_csv(r'dataset.csv')
data_1 

Disease             Symptom_1  \
0                 Fungal infection               itching   
1                 Fungal infection             skin_rash   
2                 Fungal infection               itching   
3                 Fungal infection               itching   
4                 Fungal infection               itching   
...                            ...                   ...   
4905                   Common Cold   continuous_sneezing   
4906                     Pneumonia                chills   
4907  Dimorphic hemmorhoids(piles)          constipation   
4908                  Heart attack              vomiting   
4909                Varicose veins               fatigue   

                         Symptom_2              Symptom_3  \
0                        skin_rash   nodal_skin_eruptions   
1             nodal_skin_eruptions    dischromic _patches   
2             nodal_skin_eruptions    dischromic _patches   
3                        skin_rash    dischromic _patches   
4                        skin_rash   nodal_skin_eruptions   
...                            ...                    ...   
4905                        chills                fatigue   
4906                       fatigue                  cough   
4907   pain_during_bowel_movements    pain_in_anal_region   
4908                breathlessness               sweating   
4909                        cramps               bruising   

                 Symptom_4            Symptom_5               Symptom_6  \
0      dischromic _patches                  NaN                     NaN   
1                      NaN                  NaN                     NaN   
2                      NaN                  NaN                     NaN   
3                      NaN                  NaN                     NaN   
4                      NaN                  NaN                     NaN   
...                    ...                  ...                     ...   
4905                 cough           high_fever                headache   
4906            high_fever       breathlessness                sweating   
4907          bloody_stool   irritation_in_anus                     NaN   
4908            chest_pain                  NaN                     NaN   
4909               obesity         swollen_legs   swollen_blood_vessels   

                     Symptom_7 Symptom_8    Symptom_9          Symptom_10  \
0                          NaN       NaN          NaN                 NaN   
1                          NaN       NaN          NaN                 NaN   
2                          NaN       NaN          NaN                 NaN   
3                          NaN       NaN          NaN                 NaN   
4                          NaN       NaN          NaN                 NaN   
...                        ...       ...          ...                 ...   
4905       swelled_lymph_nodes   malaise       phlegm   throat_irritation   
4906                   malaise    phlegm   chest_pain     fast_heart_rate   
4907                       NaN       NaN          NaN                 NaN   
4908                       NaN       NaN          NaN                 NaN   
4909   prominent_veins_on_calf       NaN          NaN                 NaN   

            Symptom_11       Symptom_12   Symptom_13   Symptom_14  \
0                  NaN              NaN          NaN          NaN   
1                  NaN              NaN          NaN          NaN   
2                  NaN              NaN          NaN          NaN   
3                  NaN              NaN          NaN          NaN   
4                  NaN              NaN          NaN          NaN   
...                ...              ...          ...          ...   
4905   redness_of_eyes   sinus_pressure   runny_nose   congestion   
4906      rusty_sputum              NaN          NaN          NaN   
4907               NaN              NaN          NaN          NaN   
4908               NaN              NaN          NaN     

In [7]:
data_1["Symptom_5"].unique()

array([nan, ' cough', ' chest_pain', ' loss_of_appetite',
       ' abdominal_pain', ' spotting_ urination', ' internal_itching',
       ' passage_of_gases', ' lethargy', ' sweating', ' headache',
       ' swelling_joints', ' painful_walking', ' loss_of_balance',
       ' small_dents_in_nails', ' yellow_crust_ooze',
       ' irregular_sugar_level', ' blurred_and_distorted_vision',
       ' family_history', ' mucoid_sputum', ' lack_of_concentration',
       ' excessive_hunger', ' stiff_neck', ' high_fever',
       ' yellowish_skin', ' nausea', ' fatigue', ' dark_urine',
       ' yellowing_of_eyes', ' distention_of_abdomen',
       ' history_of_alcohol_consumption', ' breathlessness',
       ' irritation_in_anus', ' swollen_legs', ' swollen_blood_vessels',
       ' dizziness', ' diarrhoea', ' unsteadiness', ' inflammatory_nails'],
      dtype=object)

In [4]:
data_1=data_1.fillna(0) # fill NAs  with 0 
data_1["Disease"].unique()
 
from sklearn import preprocessing
  
# label_encoder object knows how to understand word labels.
label_encoder = preprocessing.LabelEncoder()
  
# Encode labels in column 'species'.
data_1["Disease"]= label_encoder.fit_transform(data_1["Disease"])
  
data_1["Disease"].unique()

array([15,  4, 16,  9, 14, 33, 26, 24, 25, 31,  5,  0,  2, 38, 35, 27, 12,
       17,  6, 23, 30,  7, 32, 28, 29,  8, 11, 37, 40, 19, 20, 21, 22,  3,
       36, 10, 34, 13, 18, 39,  1])

In [5]:
# LabelEncoder

le = LabelEncoder()

data_1= data_1.apply(lambda col: le.fit_transform(col.astype(str)), axis=0, result_type='expand')
data_1
# LabelEncoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

data_1= data_1.apply(lambda col: le.fit_transform(col.astype(str)), axis=0, result_type='expand')
data_1
X = data_1.drop(['Disease','Symptom_6','Symptom_7','Symptom_8','Symptom_9','Symptom_10','Symptom_11','Symptom_12','Symptom_13','Symptom_14','Symptom_15','Symptom_16','Symptom_17'], axis=1)
y = data_1.Disease

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)

In [6]:
# KNN classifire
from sklearn.neighbors import KNeighborsClassifier
# Select an algorithm
algorithm = KNeighborsClassifier()
seed = 13
kfold = KFold(n_splits=3, shuffle=True, random_state=seed)
# Define our candidate hyperparameters
hp_candidates = [{'n_neighbors': [2,3,4,5,6], 'weights': ['uniform','distance']}]
# Search for best hyperparameters
grid = GridSearchCV(estimator=algorithm, param_grid=hp_candidates, cv=kfold, scoring='r2')
knn =grid.fit(X_train, y_train)

In [8]:
# Get the results
print(grid.best_score_)
print(grid.best_estimator_)
print(grid.best_params_) 

0.991686837774774
KNeighborsClassifier(n_neighbors=3, weights='distance')
{'n_neighbors': 3, 'weights': 'distance'}


In [9]:
# Create 3 folds

knn_predictions = knn.predict(X_test) 
cm = confusion_matrix(y_test, knn_predictions)
print(cm)
classification_report(y_test, knn_predictions)
# accuracy on X_test
accuracy = knn.score(X_test, y_test)
print(accuracy)
inverted = label_encoder.inverse_transform(knn_predictions)
print(inverted)

[[47  0  0 ...  0  0  0]
 [ 0 44  0 ...  0  0  0]
 [ 0  0 45 ...  0  0  0]
 ...
 [ 0  0  0 ... 38  0  0]
 [ 0  0  0 ...  0 36  0]
 [ 0  0  0 ...  0  0 42]]
0.9999914418713051
[31  9 14 ... 39 13 11]


In [10]:
#Naïve Bayes
from sklearn.naive_bayes import GaussianNB
gnb_clf=GaussianNB()
parameters = {
    'var_smoothing': [1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8, 1e-9, 1e-10, 1e-11, 1e-12, 1e-13, 1e-14, 1e-15]
}
clf = GridSearchCV(gnb_clf, parameters, cv=5)
gnb=clf.fit(X_train, y_train)


gnb_predictions = gnb.predict(X_test)
  
# accuracy on X_test
accuracy = gnb.score(X_test, y_test)
print(accuracy)
  
# creating a confusion matrix
cm = confusion_matrix(y_test, gnb_predictions)
print(cm)
classification_report(y_test, gnb_predictions)

inverted = label_encoder.inverse_transform(gnb_predictions)
print(inverted)

0.8556446637877854
[[41  0  0 ...  0  0  0]
 [ 0 39  0 ...  0  0  0]
 [ 0  0 43 ...  0  0  0]
 ...
 [ 0  0  0 ... 20  0  0]
 [ 0  0  0 ...  0 34  0]
 [ 0  0  0 ...  0  0 40]]
[31  9 14 ... 39 13 11]


In [16]:
import pickle
with open('model_symptom-bad','wb') as file:
    pickle.dump(gnb,file)

In [18]:
import pandas as pd
import pickle

with open('model_symptom-bad','rb') as file:
    mp = pickle.load(file)
X_test_new = [1,20,25,30,31]    
data=pd.DataFrame(X_test_new).transpose()
print(data)
pre=mp.predict(data)
print(pre)

   0   1   2   3   4
0  1  20  25  30  31
[5]


/home/dilum/.local/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [13]:
#Logistic Regression 
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import RepeatedStratifiedKFold
model = LogisticRegression(solver='liblinear')

c_values = [100, 10, 1.0, 0.1, 0.01]
# define grid search
grid = dict(C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=1, cv=cv)
grid_result = grid_search.fit(X_train, y_train)


logreg=model.fit(X_train, y_train)
log_predictions = grid_result.predict(X_test)

# accuracy on X_test
accuracy = grid_result.score(X_test, y_test)
print(accuracy)
  
# creating a confusion matrix
cm = confusion_matrix(y_test, log_predictions)
print(cm)
classification_report(y_test, log_predictions)

inverted = label_encoder.inverse_transform(log_predictions)

print(inverted)

0.7908698334361505
[[31  0  0 ...  0  0  0]
 [ 0 27  0 ...  0  0  0]
 [ 0  0 40 ...  0  0  0]
 ...
 [ 0  0  0 ... 15  0  0]
 [ 0  0  0 ...  0 30  0]
 [ 0  0  0 ...  0  0 28]]
[31  9 14 ... 39 13 11]


In [14]:
import pickle
with open('model_symptom-bad','wb') as file:
    pickle.dump(grid_result,file)

In [ ]:
import pandas as pd
import pickle

with open('model_symptom-bad','rb') as file:
    mp = pickle.load(file)
X_test_new = [0,0,0,0,0]    
data=pd.DataFrame(X_test_new).transpose()
print(data)
pre=mp.predict(X_test)
print(pre)

In [15]:

#Decision Tree algorithms
from sklearn.tree import DecisionTreeClassifier
model= DecisionTreeClassifier()
parameters={
            "max_depth" : [7,9,11,12,15],
           "min_samples_leaf":[50,10,100],
           "min_weight_fraction_leaf":[0.0001,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9],
           "max_leaf_nodes":[None,1,20,30,40,50,60,70,80,90] }

tuning_model=GridSearchCV(estimator=model,param_grid=parameters,cv=3,verbose=3)

dtree_model =tuning_model.fit(X_train, y_train)

#dtree_model = DecisionTreeClassifier(max_depth = 15).fit(X_train, y_train)
dtree_predictions = dtree_model.predict(X_test)
accuracy = dtree_model.score(X_test, y_test)
accuracy  
# creating a confusion matrix
cm = confusion_matrix(y_test, dtree_predictions)
cm

classification_report(y_test, dtree_predictions)

inverted = label_encoder.inverse_transform(dtree_predictions)

print(inverted)


Fitting 3 folds for each of 1350 candidates, totalling 4050 fits
[CV 1/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.474 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.526 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.446 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max

[CV 2/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=None, min_samples_leaf=100, min_weight_fraction_leaf

[CV 3/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=1, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=nan total time=

[CV 1/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=20, min_samples_leaf=100, min_weight_fraction_leaf=0.4;,

[CV 1/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.0001;, score=0.356 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.0001;, score=0.390

[CV 3/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=40, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan tot

[CV 2/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.478 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.385 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.1s
[CV 1/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, s

[CV 3/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan tot

[CV 3/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.474 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.531 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.446 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, sc

[CV 2/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, sco

[CV 2/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.4;,

[CV 2/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=7, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=

[CV 1/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_le

[CV 2/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=nan total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=nan total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=nan total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=nan total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=nan total time=   0.0s


[CV 1/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.479 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.480 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.476 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.3;

[CV 2/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.617 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.671 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.605 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=30, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, sc

[CV 2/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan t

[CV 1/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0

[CV 1/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.721 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.696 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.654 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=50, min_weight_fraction_leaf=0.3;

[CV 3/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.7;, score

[CV 3/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=70, min_samples_leaf=100, min_weight_fraction_leaf=0.6;,

[CV 3/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.0001;, score=0.405 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.

[CV 3/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.0001;, score=0.402 total time=   0.0s
[CV 2/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.0001;, score=0.432 total time=   0.0s
[CV 3/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.0001;, score=0.405 total time=   0.0s
[CV 1/3] END max_depth=9, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, sc

[CV 2/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.9

[CV 3/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=

[CV 1/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.482 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.484 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.476 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=20, min_samples_leaf=10, min_weight_fraction_l

[CV 2/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan

[CV 1/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.804 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.781 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.773 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_l

[CV 1/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.804 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;,

[CV 2/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=50, min_samples_leaf=100, min_weight_fraction_leaf=0.7;, s

[CV 2/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=60, min_samples_leaf=100, min_weight_fraction_le

[CV 3/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan tot

[CV 1/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=80, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, s

[CV 2/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=11, max_leaf_nodes=90, min_samples_leaf=10, min_weight_fraction_leaf=0.4;,

[CV 2/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.892 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.917 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.894 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=None, min_samples_leaf=10, min_weigh

[CV 1/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=nan to

[CV 3/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan tot

[CV 1/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.688 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.708 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.695 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_l

[CV 1/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.804 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;,

[CV 3/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_le

[CV 2/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan tot

[CV 1/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, s

[CV 3/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.89

[CV 2/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, sco

[CV 2/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=80, min_samples_leaf=100, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.800 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.771 total time=   0.1s
[CV 3/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.773 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_lea

[CV 1/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=12, max_leaf_nodes=90, min_samples_leaf=100, min_weight_fraction_leaf

[CV 1/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=None, min_samples_leaf=10, min_weight_fraction_leaf=0.9

[CV 2/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=1, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=nan total

[CV 1/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=20, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=n

[CV 1/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.688 total time=   0.1s
[CV 2/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.703 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.0001;, score=0.695 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=50, min_weight_fraction_l

[CV 2/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.4;, score=0.054 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.028 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=30, min_samples_leaf=100, min_weight_fraction_leaf=0

[CV 3/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.0001;, score=0.405 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=40, min_samples_leaf=100, min_weight_fraction

[CV 3/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=50, min_samples_leaf=10, min_weight_fraction_leaf=0.8;, score=nan t

[CV 2/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.926 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.920 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=60, min_samples_leaf=10, min_weight_fraction_leaf

[CV 3/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.8;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=50, min_weight_fraction_leaf=0.9;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=70, min_samples_leaf=10, min_weight_fraction_leaf=0.0001;, score=0.91

[CV 2/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.5;, score=0.027 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.6;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=80, min_samples_leaf=50, min_weight_fraction_leaf=0.7;, score=nan

[CV 1/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.104 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.102 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.2;, score=0.101 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.078 total time=   0.0s
[CV 3/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.3;, score=0.079 total time=   0.0s
[CV 1/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.4;, score=0.055 total time=   0.0s
[CV 2/3] END max_depth=15, max_leaf_nodes=90, min_samples_leaf=50, min_weight_fraction_leaf=0.4;,

[31  9 14 ... 39 13 11]


/home/dilum/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: 
2025 fits failed out of a total of 4050.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
1800 fits failed with the following error:
Traceback (most recent call last):
  File "/home/dilum/.local/lib/python3.9/site-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/dilum/.local/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 937, in fit
    super().fit(
  File "/home/dilum/.local/lib/python3.9/site-packages/sklearn/tree/_classes.py", line 304, in fit
    raise ValueError("min_weight_fraction_leaf must in [0, 0.5]")
ValueError: min